apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: conduit
  labels:
    app: conduit-backend
spec:
  selector:
    app: conduit-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
