apiVersion: v1
kind: ConfigMap
metadata:
  name: conduit-config
  namespace: conduit
data:
  BACKEND_PORT: "3001"
  BACKEND_NODE_ENV: "production"
  DB_HOST: "postgres"
  DB_NAME: "conduit"
  DB_DIALECT: "postgres"
  DB_LOGGING: "false"
  VITE_API_BASE_URL: "http://conduit-backend:3001"
