apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: conduit
  labels:
    app: conduit-frontend
spec:
  selector:
    app: conduit-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
