apiVersion: apps/v1
kind: Deployment
metadata:
  name: conduit-frontend
  namespace: conduit
  labels:
    app: conduit-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conduit-frontend
  template:
    metadata:
      labels:
        app: conduit-frontend
    spec:
      containers:
        - name: frontend
          image: your-dockerhub-username/conduit-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

